---
- platform: template
  sensors:
    rubbish:
      friendly_name: 'Rubbish'
      icon_template: >-
        mdi:trash-can
      value_template: >-
        {% if 'garbage' in state_attr("sensor.recollect_waste", "pickup_types") %}
         True
        {% else %}
         False
        {% endif %}
- platform: template
  sensors:
    organics:
      friendly_name: 'Organics'
      icon_template: >-
        mdi:apple
      value_template: >-
        {% if 'organics' in state_attr("sensor.recollect_waste", "pickup_types") %}
         True
        {% else %}
         False
        {% endif %}
- platform: template
  sensors:
    recycling:
      friendly_name: 'Recycling'
      icon_template: >-
        mdi:recycle
      value_template: >-
        {% if 'recycling' in state_attr("sensor.recollect_waste", "pickup_types") %}
         True
        {% else %}
         False
        {% endif %}
- platform: template
  sensors:
    garden:
      friendly_name: 'Garden'
      icon_template: >-
        mdi:flower
      value_template: >-
        {% if 'garden' in state_attr("sensor.recollect_waste", "pickup_types") %}
         True
        {% else %}
         False
        {% endif %}
- platform: template
  sensors:
    bin_collection_date:
      friendly_name: 'Bin Collection Date'
      icon_template: >-
        mdi:calendar
      value_template: >-
        {{ states("sensor.recollect_waste") }}
