---
- platform: mqtt
  state_topic: "octohc300/temperature/tool0"
  name: 'HC300 Hotend Temp'
  value_template: '{{ value_json.actual }}'
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: "octohc300/progress/printing"
  name: 'HC300 Print Progress'
  unit_of_measurement: "%"
  value_template: '{{ value_json.progress }}'
- platform: mqtt
  state_topic: "octohc300/event/PrinterStateChanged"
  name: 'HC300 Printer Status'
  value_template: '{{ value_json.state_id }}'
