---
- platform: nut
  name: "UPS"
  host: a0d7b954-nut
  username: !secret nutuser
  password: !secret nutpassword
  resources:
    - battery.charge
    - battery.runtime
    - ups.load
    - ups.status
