---
- platform: mqtt
  name: "Ensuite Light"
  state_topic: "stat/sonoffensuitelight/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoffensuitelight/POWER"
  availability_topic: "tele/sonoffensuitelight/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  