---
alias: Switch Closet Light On
initial_state: true
trigger:
  - entity_id: binary_sensor.closet_door
    from: 'off'
    platform: state
    to: 'on'
action:
  service: light.turn_on
  entity_id: light.closet
