---
alias: Switch Closet Light Off
initial_state: true
trigger:
  - entity_id: binary_sensor.closet_door
    from: 'on'
    platform: state
    to: 'off'
action:
  service: light.turn_off
  entity_id: light.closet
