---
alias: Daily Partial Backup
initial_state: true
trigger:
  - at: 02:00:00
    platform: time
condition: []
action:
  - data_template:
      name: "Partial Backup {{ now().strftime('%Y-%m-%d') }}"
      addons:
        - core_samba
        - core_deconz
        - a0d7b954_wireguard
        - a0d7b954_chrony
        - a0d7b954_nodered
        - a0d7b954_ssh
        - a0d7b954_motioneye
        - a0d7b954_adguard
        - a0d7b954_unifi
        - 15ef4d2f_esphome
      folders:
        - homeassistant
        - ssl
    service: hassio.snapshot_partial
