---
id: fe001829-5721-4a4b-a40c-a6850d773879
alias: Ender Print - Switch on Lights
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.ender_printing
    to: 'on'
action:
  service: light.turn_on
  entity_id: light.printer
