---
id: ae1e2a66-c33c-4cb6-9165-ff1a257c7a4b
alias: Front Door - Pause Timer
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.front_door_sensor_contact
    to: open
action:
  service: timer.pause
  entity_id: timer.lockdoor
