---
id: cfdd680d-e8d4-4919-bf87-3d6e3275ca38
alias: Front Door - Start Timer
initial_state: true
trigger:
  - entity_id: lock.front_door_lock
    platform: state
    to: unlocked
  - platform: state
    entity_id: binary_sensor.front_door_sensor_contact
    to: closed
action:
  - service: timer.start
    entity_id: timer.lockdoor
    data:
      duration: '00:01:00'
