---
id: b2297e6d-e327-430e-a854-e4d7e8a32d9b
alias: Notify Garage Door Open
initial_state: true
trigger:
  - entity_id: cover.garage_door
    platform: state
    to: 'open'
condition: []
action:
  - data_template:
      message: Garage Door just changed from {{ trigger.from_state.state }}
        to {{trigger.to_state.state}}
      title: Garage Door State Changed
    service: notify.pushbullet
  - data_template:
      message: Garage Door just changed from {{ trigger.from_state.state }}
        to {{trigger.to_state.state}}
      title: Garage Door State Changed
    service: notify.living_room_tv
