---
alias: Switch Guest Closet Light Off
initial_state: true
trigger:
  - entity_id: binary_sensor.guest_room_closet
    from: 'on'
    platform: state
    to: 'off'
action:
  service: light.turn_off
  entity_id: light.guest_room_closet
