---
alias: Switch Guest Closet Light On
initial_state: true
trigger:
  - entity_id: binary_sensor.guest_room_closet
    from: 'off'
    platform: state
    to: 'on'
action:
  service: light.turn_on
  entity_id: light.guest_room_closet
