---
id: b7f209e2-20f0-4942-8ac4-917ae4322361
alias: dori_away_vacuum
trigger:
  platform: state
  entity_id: binary_sensor.dori_lead_tracker
  from: 'on'
  to: 'off'
  for:
    minutes: 30
condition:
  condition: and
  conditions:
    - condition: time
      # At least one of the following is required.
      after: '06:30:00'
      before: '21:00:00'
    - condition: state
      entity_id: vacuum.roomba
      state: 'off'
      for:
        hours: 1
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
action:
  - service: vacuum.turn_on
    entity_id: vacuum.roomba
