- id: '1222205922222'
  alias: Lock Front Door after 5 minutes
  trigger:
  - entity_id: lock.front_door_lock
    for:
      minutes: 5
    platform: state
    to: unlocked
  condition:
  - condition: state
    entity_id: binary_sensor.front_door
    state: Closed
  action:
  - entity_id: lock.front_door_lock
    service: lock.lock
- alias: A8 Print - Switch on Lights
  id: '1795389913795'
  trigger:
  - platform: state
    entity_id: sensor.anet_printer_status
    to: PRINTING
  action:
    service: light.turn_on
    entity_id: light.spare_room
- alias: Turn HC Off Post Print
  id: '142105927354'
  trigger:
  - entity_id: sensor.hc_printer_status
    from: PRINTING
    platform: state
    to: OPERATIONAL
  action:
    service: switch.turn_off
    entity_id: switch.hypercube_power
- alias: HC Print - Switch on Lights
  id: '1299648504932'
  trigger:
  - platform: state
    entity_id: sensor.hc_printer_status
    to: PRINTING
  action:
    service: light.turn_on
    entity_id: light.spare_room
- alias: Power state on HA start-up
  id: '9999205888822'
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffensuitelight/POWER
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffensuitefan/POWER
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/sonofftlm/POWER
      payload: ''
  - service: mqtt.publish
    data:
      topic: garage/door/1/action
      payload: STATE
- id: '1543010233580'
  alias: Notify Garage Door
  trigger:
  - entity_id: cover.garage_door
    platform: state
  condition: []
  action:
  - data_template:
      message: Garage Door just changed from {{ trigger.from_state.state }} to {{trigger.to_state.state
        }}
      title: Garage Door State Changed
    service: notify.pushbullet
  - data_template:
      message: Garage Door just changed from {{ trigger.from_state.state }} to {{trigger.to_state.state
        }}
      title: Garage Door State Changed
    service: notify.living_room_tv
- id: '1543199137368'
  alias: Daily Backup
  trigger:
  - at: 02:00:00
    platform: time
  condition: []
  action:
  - data:
      addon: ce20243c_remote_backup
    service: hassio.addon_start
