---
title: Home
resources: !include_dir_list lovelace/resources
views:
  - !include lovelace/views/main.yaml
  - !include lovelace/views/temperature.yaml
  - !include lovelace/views/printers.yaml
  - !include lovelace/views/nest.yaml
  - !include lovelace/views/camera.yaml
  - !include lovelace/views/blink.yaml
  