---
title: Home
resources: !include_dir_list lovelace/resources
custom_header:
  compact_mode: true
  hide_help: true
  hide_config: true
views:
  - !include lovelace/views/main.yaml
  - !include lovelace/views/temperature.yaml
  - !include lovelace/views/printers.yaml
  - !include lovelace/views/nest.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/blink.yaml
