---
title: Home
resources: !include_dir_list lovelace/resources
cch:
  menu: show
  options: clock
  voice: hide
  clock_format: 24
views:
  - !include lovelace/views/main.yaml
  - !include lovelace/views/temperature.yaml
  - !include lovelace/views/printers.yaml
  - !include lovelace/views/nest.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/blink.yaml
