---
- platform: template
  switches:
    armed:
      friendly_name: 'Blink Armed Toggle'
      value_template: "{{ is_state('alarm_control_panel.blink_sync' , 'armed_away') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.arm_blink
      turn_off:
        service: script.turn_on
        entity_id: script.disarm_blink
- platform: template
  switches:
    frontmotion:
      friendly_name: 'Blink Front Motion'
      value_template: "{{ is_state('binary_sensor.blink_front_camera_armed' , 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.blink_motion_on_front
      turn_off:
        service: script.turn_on
        entity_id: script.blink_motion_off_front
- platform: template
  switches:
    backmotion:
      friendly_name: 'Blink Back Motion'
      value_template: "{{ is_state('binary_sensor.blink_back_camera_armed' , 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.blink_motion_on_back
      turn_off:
        service: script.turn_on
        entity_id: script.blink_motion_off_back
- platform: template
  switches:
    sidemotion:
      friendly_name: 'Blink Side Motion'
      value_template: "{{ is_state('binary_sensor.blink_side_camera_armed' , 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.blink_motion_on_side
      turn_off:
        service: script.turn_on
        entity_id: script.blink_motion_off_side
