---
homeassistant:

  customize: !include_dir_merge_named ../../customisations/entities
  customize_glob: !include_dir_merge_named ../../customisations/globs
  #customize_domain: !include_dir_merge_named ../../customisations/domains
  