---
- platform: mqtt
  name: "Sonoff HA"
  state_topic: "stat/sonoffha/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoffha/POWER"
  availability_topic: "tele/sonoffha/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  