---
- platform: mqtt
  name: "Ensuite Fan"
  state_topic: "stat/sonoffensuitefan/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoffensuitefan/POWER"
  availability_topic: "tele/sonoffensuitefan/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
