---
esphomeyaml:
  name: bedsidelight2
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  domain: !secret dnsdomain
  ssid: !secret wifi
  password: !secret wifipass
  manual_ip:
    static_ip: !secret bedsidel2ip
    gateway: !secret iotgateway
    subnet: !secret iotsubnet
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret otapass

ota:
  password: !secret otapass

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "Bedside Light 2 Button"
    on_press:
      then:
       - switch.toggle: switch_main
    internal: yes
  - platform: status
    name: "Bedside Light 2 Status"

switch:
  - platform: gpio
    id: relay
    name: "Internal Relay"
    pin: GPIO15
    restore_mode: always off
    internal: yes
  - platform: template
    id: switch_main
    name: "Bedside Light 2 Switch"
    lambda: return id(relay).state;
    turn_on_action:
      then:
       - switch.turn_on: relay
       - light.turn_on: blueled
    turn_off_action:
      then:
       - switch.turn_off: relay
       - light.turn_off: blueled

output:
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO2
      inverted: True
  - platform: esp8266_pwm
    id: red_led
    pin:
      number: GPIO0
      inverted: True

light:
  - platform: monochromatic
    name: "Bedside Light 2 Blue LED"
    output: blue_led
    id: blueled
    internal: yes
  - platform: monochromatic
    name: "Bedside Light 2 Red LED"
    output: red_led
