---
esphomeyaml:
  name: tlmswitchpow
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  domain: !secret dnsdomain
  ssid: !secret wifi
  password: !secret wifipass
  manual_ip:
    static_ip: !secret tlmswitchip
    gateway: !secret iotgateway
    subnet: !secret iotsubnet
# Enable logging
logger:
  baud_rate: 0
# Enable Home Assistant API
api:
  password: !secret otapass

ota:
  password: !secret otapass

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "TLM Switch Button"
    internal: true
    on_press:
      - switch.toggle: switch_main

switch:
  - platform: gpio
    name: "TLM Switch Relay"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON
    internal: true
  - platform: template
    id: switch_main
    name: "TLM Power Switch"
    lambda: return id(relay).state;
    turn_on_action:
      then:
        - switch.turn_on: relay
        - light.turn_on: tlm_switch_led
    turn_off_action:
      then:
        - switch.turn_off: relay
        - light.turn_off: tlm_switch_led

output:
  - platform: esp8266_pwm
    id: tlm_switch_internal_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    name: "TLM Switch LED"
    output: tlm_switch_internal_led
    internal: true
    id: tlm_switch_led

sensor:
  - platform: cse7766
    current:
      name: "TLM Switch Current"
    voltage:
      name: "TLM Switch Voltage"
    power:
      name: "TLM Switch Power"
