---
alias: Power state on HA start-up
initial_state: true
trigger:
  platform: homeassistant
  event: start
action:
  - service: mqtt.publish
    data:
      topic: garage/door/1/action
      payload: STATE

