alias: Turn HC Off Post Print
trigger:
- entity_id: sensor.hc_printer_status
  from: PRINTING
  platform: state
  to: OPERATIONAL
action:
  service: switch.turn_off
  entity_id: switch.hypercube_power