- platform: mqtt
  state_topic: "spareroom/sensor/spare_room_brightness/state"
  name: 'Spare Room Brightness'
  unit_of_measurement: "lux"
  availability_topic: "spareroom/status"
  expire_after: 45
  icon: "mdi:flash"
- platform: mqtt
  state_topic: "spareroom/sensor/spare_room_humidity/state"
  name: 'Spare Room Humidity'
  unit_of_measurement: "%"
  availability_topic: "spareroom/status"
  expire_after: 675
  icon: "mdi:water-percent"
- platform: mqtt
  state_topic: "spareroom/sensor/spare_room_temperature/state"
  name: 'Spare Room Temperature'
  unit_of_measurement: "°C"
  availability_topic: "spareroom/status"
  expire_after: 675