---
esphome:
  name: bletracker
  platform: ESP32
  board: featheresp32

wifi:
  domain: !secret dnsdomain
  ssid: !secret wifi2
  password: !secret wifipass
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret otapass

ota:
  password: !secret otapass

esp32_ble_tracker:

binary_sensor:
  - platform: ble_presence
    device_class: presence
    mac_address: !secret doritracker
    name: "Dori Lead Tracker"

sensor:
  - platform: uptime
    name: "BLE Uptime Sensor"
  - platform: ble_rssi
    mac_address: !secret doritracker
    name: "Dori Lead Tracker RSSI value"
