---
esphome:
  name: lightstrip
  platform: ESP32
  board: featheresp32

wifi:
  domain: !secret dnsdomain
  ssid: !secret wifi2
  password: !secret wifipass
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret otapass

ota:
  password: !secret otapass

esp32_ble_tracker:

binary_sensor:
  - platform: ble_presence
    device_class: presence
    mac_address: !secret doritracker
    name: "Dori Lead Tracker"

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO21
    num_leds: 149
    rgb_order: GRB
    name: "Living Room Light Strip"
    effects:
      - random:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
      - addressable_lambda:
          name: "My Custom Effect"
          update_interval: 100ms
          lambda: |-
            // it.size() - Number of LEDs
            // it[num] - Access the LED at index num.
            // Set the LED at num to the given r, g, b values
            // it[num] = light::ESPColor(r, g, b);
            // Get the color at index num (ESPColor instance)
            // it[num].get();
            // Example: Simple color wipe
            for (int i = 1; i < it.size(); i++) {
              it[i] = it[i - 1].get();
            }
            it[0] = light::ESPColor::random_color();

sensor:
  - platform: uptime
    name: "Light Strip Uptime Sensor"
  - platform: ble_rssi
    mac_address: !secret doritracker
    name: "Dori Lead Tracker RSSI value"
