---
esphome:
  name: lightstrip
  platform: ESP32
  board: featheresp32

wifi:
  domain: !secret dnsdomain
  ssid: !secret wifi
  password: !secret wifipass
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret otapass

ota:
  password: !secret otapass

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO21
    num_leds: 149
    rgb_order: GRB
    name: "Living Room Light Strip"
    effects:
      - random:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:

sensor:
  - platform: uptime
    name: "Light Strip Uptime Sensor"
