---
esphome:
  name: merkury1
  platform: ESP8266
  board: esp01_1m

wifi:
  domain: !secret dnsdomain
  ssid: !secret wifi
  password: !secret wifipass

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret otapass

ota:
  password: !secret otapass

power_supply:
  - id: rgb_power
    pin: GPIO13

output:
  - platform: esp8266_pwm
    pin: GPIO5
    frequency: 1000 Hz
    id: pwm_w

light:
  - platform: monochromatic
    name: 'Merkury 1 Bulb White'
    output: pwm_w
  - platform: fastled_spi
    name: "Merkury 1 Bulb RGB"
    chipset: SM16716
    clock_pin: GPIO4
    data_pin: GPIO14
    power_supply: rgb_power
    num_leds: 8
    rgb_order: RGB

sensor:
  - platform: uptime
    name: "Merkury1 Uptime Sensor"
