---
esphome:
  name: teckinpow
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  domain: !secret dnsdomain
  ssid: !secret wifi
  password: !secret wifipass

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret otapass

ota:
  password: !secret otapass

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "Teckin Pow  Button"
    on_press:
      then:
        - switch.toggle: switch_main
    internal: true
  - platform: status
    name: "Teckin Pow  Status"
switch:
  - platform: gpio
    id: relay
    name: "Internal Relay"
    pin: GPIO4
    restore_mode: always off
    internal: true
  - platform: template
    id: switch_main
    name: "Teckin Pow Switch"
    lambda: return id(relay).state;
    turn_on_action:
      then:
        - switch.turn_on: relay
        - light.turn_on: blueled
    turn_off_action:
      then:
        - switch.turn_off: relay
        - light.turn_off: blueled

output:
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO2
      inverted: true
  - platform: esp8266_pwm
    id: red_led
    pin:
      number: GPIO0
      inverted: true

light:
  - platform: monochromatic
    name: "Teckin Pow Blue LED"
    output: blue_led
    id: blueled
    internal: true
  - platform: monochromatic
    name: "Teckin Pow Red LED"
    output: red_led

sensor:
  - platform: uptime
    name: "Teckin Pow Uptime Sensor"
  - platform: hlw8012
    sel_pin: 
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: 0.00221
    voltage_divider: 871
    current:
      name: "Teckin Pow Current"
      unit_of_measurement: A
    voltage:
      name: "Teckin Pow voltage"
      unit_of_measurement: V
    power:
      name: "Teckin Pow power"
      id: my_power
      unit_of_measurement: W
    change_mode_every: 8
    update_interval: 10s
