---
esphome:
  name: teckinoutdoor
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  domain: !secret dnsdomain
  ssid: !secret wifi
  password: !secret wifipass
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret otapass

ota:
  password: !secret otapass

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "Teckin Outdoor Button"
    on_press:
      then:
        - switch.toggle: switch_main1
    internal: true
  - platform: status
    name: "Teckin Outdoor Status"

switch:
  - platform: gpio
    id: relay1
    name: "Internal Relay 1"
    pin: GPIO14
    restore_mode: always off
    internal: true
  - platform: gpio
    id: relay2
    name: "Internal Relay 2"
    pin: GPIO12
    restore_mode: always off
    internal: true
  - platform: template
    id: switch_main1
    name: "Teckin Outdoor Switch 1"
    lambda: return id(relay1).state;
    turn_on_action:
      then:
        - switch.turn_on: relay1
        - light.turn_on: blueled
    turn_off_action:
      then:
        - switch.turn_off: relay1
        - light.turn_off: blueled

output:
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO4
      inverted: true
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO5
      inverted: true

light:
  - platform: monochromatic
    name: "Teckin Outdoor Blue LED"
    output: blue_led
    id: blueled
    internal: true
  - platform: monochromatic
    name: "Teckin Outdoor Blue LED"
    output: green_led
    id: greenled
    internal: true
