---
substitutions:
  device_name: tlmcamera  # hostname & entity_id
  friendly_name: TLM Camera   # Displayed in HA frontend

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  domain: !secret dnsdomain
  ssid: !secret wifi2
  password: !secret wifipass
  
web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret otapass

ota:
  password: !secret otapass

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: ${friendly_name} Button
    on_press:
      then:
        - switch.toggle: switch_main
    internal: true
  - platform: status
    name: ${friendly_name} Status

switch:
  - platform: gpio
    id: relay
    name: "Internal Relay"
    pin: GPIO15
    restore_mode: always off
    internal: true
  - platform: template
    id: switch_main
    name: ${friendly_name} Switch
    lambda: return id(relay).state;
    turn_on_action:
      then:
        - switch.turn_on: relay
        - light.turn_on: blueled
    turn_off_action:
      then:
        - switch.turn_off: relay
        - light.turn_off: blueled

output:
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO2
      inverted: true
  - platform: esp8266_pwm
    id: red_led
    pin:
      number: GPIO0
      inverted: true

light:
  - platform: monochromatic
    name: ${friendly_name} Blue LED
    output: blue_led
    id: blueled
    internal: true
  - platform: monochromatic
    name: ${friendly_name} Red LED
    output: red_led

sensor:
  - platform: uptime
    name: ${friendly_name} Uptime Sensor
