name: Config Check
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *
jobs:
  configcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running ha check
        uses: sinclairpaul/ha-action@master