---
name: Config Check
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *
jobs:
  configchecklatest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running ha check latest
        uses: sinclairpaul/ha-action@master
  configcheckrc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running ha check rc
        uses: sinclairpaul/ha-action@master
        with:
          habranch: rc
  configcheckdev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running ha check dev
        uses: sinclairpaul/ha-action@master
        with:
          habranch: dev
