---
name: Config Check
on:
  push:
  pull_request:
  schedule:
    - cron: 0 22 * * *
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Prepare
        run: pip install --user yamllint
      - name: Show yamllint version
        run:  yamllint --version
      - name: yamllint
        run: yamllint . 
