---
name: HA Config Check
on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
  schedule:
    - cron: 0 22 * * *
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running yamllint version
        uses: ./.github/actions/linting/yamllint
        with:
          entrypoint: yamllint
          args: --version
      - name: Running yamllint
        uses: ./.github/actions/linting/yamllint
        with:
          entrypoint: yamllint
          args: .
  mdllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running mdl version
        uses: ./.github/actions/linting/markdown
        with:
          entrypoint: mdl
          args: --version
      - name: Running mdl
        uses: ./.github/actions/linting/markdown
        with:
          entrypoint: mdl
          args: --style all --warnings .
  haconfig:
    needs: [yamllint, mdllint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running ha check latest
        uses: sinclairpaul/ha-configcheck@v0.0.1
      - name: Running ha check rc
        uses: ./.github/actions/hacheck/rc
      - name: Running ha check dev
        uses: ./.github/actions/hacheck/dev
  esphome:
    needs: [yamllint, mdllint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running esphome check latest
        uses: ./.github/actions/esphome/latest
      - name: Running esphome check beta
        uses: ./.github/actions/esphome/beta
