---
name: Config Check
on:
  push:
  pull_request:
  schedule:
    - cron: 0 22 * * *
jobs:
  configchecklatest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running ha check latest
        uses: ./.github/actions/hachecklatest
  configcheckrc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running ha check rc
        uses: ./.github/actions/hacheckrc
  configcheckdev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running ha check dev
        uses: ./.github/actions/hacheckdev
