---
name: HA Config Check
on:  # yamllint disable-truthy
  push:
  pull_request:
  schedule:
    - cron: 0 22 * * *
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running yamllint version
        uses: ./.github/actions/linting/yamllint
        with:
          entrypoint: yamllint
          args: --version
      - name: Running yamllint
        uses: ./.github/actions/linting/yamllint
        with:
          entrypoint: yamllint
          args: .
  haconfig:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running ha check latest
        uses: ./.github/actions/hacheck/latest
      - name: Running ha check rc
        uses: ./.github/actions/hacheck/rc
      - name: Running ha check dev
        uses: ./.github/actions/hacheck/dev
  esphome:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config
        uses: actions/checkout@v1.0.0
      - name: Running esphome check latest
        uses: ./.github/actions/esphome/latest
      - name: Running esphome check beta
        uses: ./.github/actions/esphome/beta
